#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define _BASE 0
#define _LAYER_1 1

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	
	/* ,--------------------.
	 * | LYR1 | NEXT | MUTE |
	 * |------+------+------|
	 * | PLAY | VOL- | VOL+ |
	 * `--------------------' */

	[_BASE] = LAYOUT(
		KC_MUTE, KC_VOLU, KC_MNXT, KC_VOLD, MO(_LAYER_1), KC_MPLY
		),

	/* ,--------------------.
	 * | TRNS | PREV | MUTE |
	 * |------+------+------|
	 * | PLAY | VOL- | RSET |
	 * `--------------------' */

	[_LAYER_1] = LAYOUT(
		KC_MUTE, RESET, KC_MPRV, KC_VOLD, KC_TRANSPARENT, KC_MPLY
		)
};
